### ISSUE TITLE
Uncaught RangeError: Applying a mismatched transaction

### ISSUE THREAD

**Issue by QuentinCWG** [Cassielxd/CassieEditor#1]
<img width="1627" alt="Screenshot 2024-02-21 at 7 00 05 AM" src="https://github.com/Cassielxd/CassieEditor/assets/9435937/5886ab74-baa6-4dc2-9ec2-004f9be942db">

Inserting `<strong>T-bone pancetta turkey pastrami porchetta. Sirloin ham salami andouille. Sirloin meatloaf ham hock, tail spare ribs venison pastrami hamburger leberkas pancetta flank porchetta jowlhamburger leberkas pancetta flank porchetta jowl.</strong>` will break implementation and the editor, resulting in an `RangeError: Maximum call stack size exceeded` and a `Uncaught RangeError: Applying a mismatched transaction.` Tested off of main branch and `http://39.101.177.50/#/page1`.

**Comment by QuentinCWG** [comment]
I don't think this should have been closed, I am still seeing this issue and it has not been fixed

**Comment by QuentinCWG** [comment]
@Cassielxd let me know if you need to me send a video or reproducing steps

**Comment by QuentinCWG** [comment]
Video here https://www.loom.com/share/2bf84049d3b64c319fe94148cc0162ef

**Comment by Cassielxd** [comment]
You can try pulling the code again, as this project has just been open source for a while

The boundary handling of some operations is not yet perfect and is being gradually improved. Thank you for raising the question

**Comment by Cassielxd** [comment]
https://www.loom.com/share/229be7c1c9924a04aef8d8e5abe0c4fe
